# Generated by Django 5.1.3 on 2024-12-13 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0008_rename_user_contact_username_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskUsers',
            new_name='TaskUser',
        ),
        migrations.RenameModel(
            old_name='UserContacts',
            new_name='UserContact',
        ),
    ]
