# Generated by Django 5.1.3 on 2024-12-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0015_contact_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ContactUserDetails',
        ),
    ]
