# Generated by Django 5.1.3 on 2024-12-29 11:50

from django.core.validators import EmailValidator
from django.db import migrations, models
from user_auth_app.api.validators import validate_phone_format, validate_username_format


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0016_remove_contact_created_by_delete_contactuserdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(
                max_length=254,
                validators=[
                    EmailValidator(
                        message="Enter a valid email domain"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, validators=[validate_username_format]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, validators=[validate_phone_format]),
        ),
    ]
