# Generated by Django 5.1.3 on 2024-12-29 11:50

import join_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0016_remove_contact_created_by_delete_contactuserdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, validators=[join_app.models.validate_email_format]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
