# Generated by Django 5.1.3 on 2024-12-29 11:54

import join_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0017_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, validators=[join_app.models.validate_phone_format]),
        ),
    ]
