# Generated by Django 5.1.3 on 2024-12-30 09:03

import user_auth_app.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0018_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, validators=[user_auth_app.api.validators.validate_username_format]),
        ),
    ]
