# Generated by Django 5.1.3 on 2024-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0019_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Enter a valid email address'}, max_length=254, unique=True),
        ),
    ]
