# Generated by Django 5.1.3 on 2024-12-30 21:11

import user_auth_app.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0020_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(error_messages={'max_length': 'Phone number cannot exceed 13 characters.'}, max_length=13, validators=[user_auth_app.api.validators.validate_phone_format]),
        ),
    ]
