# Generated by Django 5.1.3 on 2024-12-30 22:47

import user_auth_app.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0021_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(error_messages={'email': 'Enter a valid email address'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13, validators=[user_auth_app.api.validators.validate_phone_format]),
        ),
    ]
