# Generated by Django 5.1.3 on 2024-12-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_customuser_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='123456789', max_length=13),
        ),
    ]
