# Generated by Django 5.1.3 on 2024-12-30 09:03

import user_auth_app.api.validators
from django.db import migrations, models
from django.core.validators import EmailValidator
from user_auth_app.api.validators import validate_phone_format, validate_username_format


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    EmailValidator(
                        message="Enter a valid email domain"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='123456789', max_length=13, validators=[validate_phone_format]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                help_text='50 Zeichen oder weniger. Buchstaben, Zahlen, Leerzeichen und @/./+/-/_ erlaubt.',
                max_length=50,
                unique=True,
                validators=[validate_username_format]
            ),
        ),
    ]
