# Generated by Django 5.1.3 on 2024-12-30 11:34

import user_auth_app.api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0005_alter_customuser_email_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[user_auth_app.api.validators.validate_username_format]),
        ),
    ]
